repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: [--follow-imports=skip, --disable-error-code=attr-defined]
        additional_dependencies:
          [
            loguru==0.6.0,
            loguru-mypy==0.0.4,
            pydantic>=1.9.1,
            types-python-dateutil==2.8.19.4,
          ]